notification:
  service: |
    voucherService : 1
    blackListManagementService : 2
    (type exist if you want to exist)
  voucherPrompt: |
    ==== Voucher Program ===
    Type **create** to create a new voucher.
    Type **lookup** to lookup list all vouchers.
  voucherTypeChoice: |
    Choose one!
    fixedVoucher: 1
    PercentVoucher: 2
  wrongInput: It's wrong input
  exit: Good bye!


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/voucher_mgmt
    username: root
    password: root1234!
    type: com.zaxxer.hikari.HikariDataSource
